#10  : Add payload validator
boms-student/boms-users-api pull request #18
Opened 2022-04-03 09:56 UTC by raghavdhupar7

#10  :Added  params validation to GET@/users/:userId, PUT@/users/:userId, and DELETE@/users/:userId
Added body validation to PUT@/users/:userId, and POST@/users/:userId

2022-04-03 10:12 UTC, tanayhub requested changes

2022-04-03 10:12 UTC, tanayhub commented on routes/users.js
> +router.get("/", RequestValidator(userSchema), async (req, res, next) => {
why would `GET` requests need params/body validators?

2022-04-03 10:12 UTC, tanayhub commented on routes/users.js
> +router.get("/:userId", RequestValidator(userSchema), async (req, res, next) => {
same

2022-04-03 10:12 UTC, tanayhub commented on routes/users.js
> +router.delete(
same

2022-04-03 10:12 UTC, tanayhub commented on routes/users.js
> +router.delete("/", RequestValidator(userSchema), async (req, res, next) => {
same

2022-04-03 10:23 UTC, raghavdhupar7 commented on routes/users.js
> +router.get("/", RequestValidator(userSchema), async (req, res, next) => {
was mentioned in the description of the story

2022-04-04 12:07 UTC, tanayhub approved these changes

2022-04-04 12:08 UTC, merged